Update scrumblr
YunoHost-Apps/scrumblr_ynh pull request #16
Opened 2021-12-28 14:22 UTC by oiseauroch

Hello, scrumblr is no more actively maintained. I discussed with colibri team to use their own repository with app debranded.

This version should allow to install scrumblr in a subpath. 
Moreover, scrumblr uses a redis database to store data. Currently, the database is not saved and redis doesn't really allow to save a unique database. This new version spawn a specific redis process for scrumblr so that it can be backup and restored.

2021-12-28 14:22 UTC, oiseauroch commented
!testme

2021-12-28 15:02 UTC, ericgaspar requested changes

2021-12-28 15:02 UTC, ericgaspar commented on manifest.json
>          "code": "https://github.com/aliasaria/scrumblr"
```suggestion
        "code": "https://framagit.org/colibris/framemo"
```

2021-12-28 15:08 UTC, ericgaspar commented
Thanks for taking care of this app!

Do we need to reinstall redis-server pkg, service and config file knowing that it is installed in YunoHost as default?

2021-12-28 15:18 UTC, oiseauroch commented
we do not need to reinstall redis-server pkg but it's just in case redis wouldn't be a yunohost dependency anymore. 

Custom service and config files are necessary to spawn a custom process of redis.

2021-12-28 16:10 UTC, ericgaspar commented
Redis is served with the address `127.0.0.1:6379` (this is also set in the framemo `config.js` file. Do we need to define another port (8081) and not use the default one (6379)?

2021-12-28 16:51 UTC, oiseauroch commented
Normaly this settings are overwritten in the systemd config files. 
- the `scrumblr_redis.service` file call `redis-server` with custom config file that set specific port 
- the `systemd.service` file overwrite settings from the config file with argument parameters.

2021-12-29 20:45 UTC, oiseauroch commented
!testme

2021-12-30 08:25 UTC, oiseauroch commented
!testme

2021-12-30 14:15 UTC, oiseauroch commented
!testme

2021-12-31 08:55 UTC, oiseauroch commented
!testme

2022-01-01 14:24 UTC, oiseauroch commented
!testme

2022-01-02 20:13 UTC, ericgaspar requested changes
We need to remove the logs in the remove script 

```
ynh_secure_remove --file="/var/log/$app"
```

2022-01-10 08:35 UTC, ericgaspar commented
!testme

2022-01-11 21:17 UTC, oiseauroch commented
@ericgaspar it seems that the yunohost container has a problem with the redis service. (https://github.com/YunoHost/issues/issues/1962)
Trying to install the old version of scrumblr on a fresh container will success but the application will never be able to reach redis because it doesn't start. 
And then updating from the previous version try to connect to redis and fails.

2022-01-12 11:37 UTC, oiseauroch commented
I was wrong in my previous comment. 
!testme

2022-01-13 20:59 UTC, ericgaspar approved these changes

2022-01-13 21:02 UTC, ericgaspar commented
@oiseauroch you should have write access to this repo now

2022-01-15 13:32 UTC, oiseauroch commented
@ericgaspar Thanks a lot for all advice and support.

2022-01-15 13:32 UTC, merged